### ISSUE TITLE
Giving view-ids uniquely

### ISSUE THREAD

**Issue by keighrim** [lappsgrid-incubator/tcf-converter-prototype#20]
Currently implementation (roughly a LIF view for a TCF layer) requires some views necessarily back-refer to a previous view (for instance, `dependency-view` in #19 depends on `token-view`). 
This can be a problem, if there are two or more TCF-LIF conversion in the workflow, in that the converter service does not give a unique view-id to the views it generates. Thus, for example, the `token-view`s from all the conversions would share the same view-id (currently `token-view`) , which then confuses any view that depends on one of them. 

Two ways to solve this: 

1. A method to read all previous views and count the number of TCF-LIF conversions that have occurred to find out a proper view-id's for the current conversion. 
1. A unique view-id generation either pseudo-randomly, or based on the timestamp.

**Comment by ksuderman** [comment]
If using option 2 I would suggest using a UUID either using `java.util.UUID.randomUUID().toString()` or the http://api.lappsgrid.org/uuid service

Another alternative would be to use something like `'v-' + (views.size() + 1)`

**Comment by ksuderman** [comment]
We need to re-examine this issue as the Container.newView() methods will now always ensure that all views in the container have unique IDs.

**Comment by ksuderman** [comment]
Fixed by 5097eb7fb9c1925b17fd8513b096ce93c4622dec
