### ISSUE TITLE
Duplicate start id of two different tokens in LIF (on TCF to LIF converter)

### ISSUE THREAD

**Issue by ksuderman** [lappsgrid-incubator/tcf-converter-prototype#21]
_From @elahi123 on September 4, 2018 13:58_

TCF to LIF converter sometimes generate wrong start ids. In the following example, two different (included, in) tokens have duplicate start id.  
Here is an example of 
[LIF-output.txt](https://github.com/lapps-clarin/converter-issues/files/2348886/LIF-output.txt)
[Tcf_Input.txt](https://github.com/lapps-clarin/converter-issues/files/2348891/Tcf_Input.txt)

duplicate start id of two tokens.

{
                        "id": "t_148",
                        "start": **791**,
                        "end": 799,
                        "@type": "http://vocab.lappsgrid.org/Token",
                        "features": {
                            "word": "included",
                            "pos": "VBN"
                        }
                    }, {
                        "id": "t_149",
                        "start": **791**,
                        "end": 793,
                        "@type": "http://vocab.lappsgrid.org/Token",
                        "features": {
                            "word": "in",
                            "pos": "IN"
                        }
                    }, 

_Copied from original issue: lapps-clarin/converter-issues#8_

**Comment by ksuderman** [comment]
I've deployed a new version that should fix this.  See https://github.com/lappsgrid-services/org.lappsgrid.converters.tcf/pull/24

Can you test again?

**Comment by elahi123** [comment]
The issue is hard to re-create. I found the duplicate start id for the attached file Tcf_Input.txt given above. Since that file now works fine, I assume the issue is resolved.
